// Generated by scripts/sync-minigames.mjs.
import type { MinigameCheck } from './check.editor'
import check0 from './carry/check.editor'
import check1 from './combat/check.editor'
import check2 from './estate/check.editor'
import check3 from './powerstrike/check.editor'
import check4 from './quickhands/check.editor'

export const minigameChecks = new Map<string, MinigameCheck>([
  ['carry', check0],
  ['combat', check1],
  ['estate', check2],
  ['powerstrike', check3],
  ['quickhands', check4],
])
