// Generated by scripts/sync-minigames.mjs; add a <kind>/data.ts module to register a kind.
import module0 from './carry/data'
export * from './carry/data'
import module1 from './combat/data'
export * from './combat/data'
import module2 from './estate/data'
export * from './estate/data'
import module3 from './powerstrike/data'
export * from './powerstrike/data'
import module4 from './quickhands/data'
export * from './quickhands/data'

const modules = [module0, module1, module2, module3, module4] as const
export type MinigameDefinition = ReturnType<(typeof modules)[number]['create']>
export const minigameModules = new Map<string, (typeof modules)[number]>()
for (const module of modules) {
  if (minigameModules.has(module.kind)) throw new Error(`Duplicate minigame kind: ${module.kind}`)
  minigameModules.set(module.kind, module)
}
