import { INVENTORY, ITEM_LIST, type StatsDocument, type Variable } from "./statsDoc";
import { emptyNpcs, npcVar, type NpcDocument } from "./bundle/npcDoc";

/**
 * The catalogue, as ink declarations.
 *
 * Generated rather than hand-written, and regenerated whole on every change.
 * That is safe precisely because the file holds nothing else: it is declarations
 * and comments, so there is no authored prose to preserve and no possibility of
 * losing a line to a round trip. Everything that *uses* these names lives in the
 * story files, written by hand or by the GUI, and is never touched from here.
 *
 * One `LIST` holding every item, feeding a single inventory variable — which is
 * what makes `inventory ? shovel` work. It was once one list per author-named
 * category, which asked for a second name for every item: one for the thing and
 * one for the box it went in.
 */

/** Where the generated declarations live, project-relative. */
export const STATE_FILE = "ink/state.ink";

const HEADER = `// Variables, items and cast state for this story.
//
// Generated by InkCrafter from stats.json and npcs.json — edit the catalogues,
// not this file. Anything added here by hand is lost the next time it is
// regenerated.
//
// One generated file, deliberately. Two would be two things able to declare the
// same name, and a duplicate VAR is a compile error rather than a warning.`;

/** A stat or hidden variable's starting value as ink source. */
export function initialLiteral(variable: Variable): string {
  if (variable.kind === "boolean") return variable.initial === true ? "true" : "false";
  if (variable.kind === "text") {
    // Ink has no escape for a quote inside a string literal, so one is dropped
    // rather than allowed to end the string early and break the declaration.
    return `"${String(variable.initial).replace(/"/g, "")}"`;
  }
  return Number.isFinite(Number(variable.initial))
    ? String(Number(variable.initial))
    : "0";
}

export function renderStateInk(
  doc: StatsDocument,
  npcs: NpcDocument = emptyNpcs(),
): string {
  const lines: string[] = [HEADER, ""];

  if (doc.stats.length > 0) {
    lines.push("// Stats shown to the player.");
    for (const stat of doc.stats) {
      if (stat.description.trim().length > 0) {
        lines.push(`// ${stat.description.trim().replace(/\s*\n\s*/g, " ")}`);
      }
      lines.push(`VAR ${stat.name} = ${initialLiteral(stat)}`);
    }
    lines.push("");
  }

  if (doc.variables.length > 0) {
    lines.push("// Hidden story variables.");
    for (const variable of doc.variables) {
      if (variable.description.trim().length > 0) {
        lines.push(`// ${variable.description.trim().replace(/\s*\n\s*/g, " ")}`);
      }
      lines.push(`VAR ${variable.name} = ${initialLiteral(variable)}`);
    }
    lines.push("");
  }

  if (doc.items.length > 0) {
    lines.push("// Everything that can be carried.");
    lines.push(`LIST ${ITEM_LIST} = ${doc.items.map((item) => item.name).join(", ")}`);
    lines.push("");
    lines.push(
      "// What the player is carrying. The game owns this at runtime.",
    );
    lines.push(`VAR ${INVENTORY} = ()`);
    lines.push("");
  }

  if (npcs.npcs.length > 0) {
    lines.push("// The cast, and what the story tracks about them.");
    for (const npc of npcs.npcs) {
      lines.push(`// ${npc.name}`);
      for (const variable of npc.variables) {
        // One list of three kinds now, so the declaration is chosen per row
        // rather than per loop. The names and literals are unchanged: a story
        // written against the old three-list catalogue still compiles.
        const literal =
          variable.kind === "number"
            ? String(Math.round(Number(variable.initial) || 0))
            : variable.kind === "boolean"
              ? variable.initial === true
                ? "true"
                : "false"
              : `"${inkString(String(variable.initial))}"`;

        lines.push(`VAR ${npcVar(npc.inkId, variable.key)} = ${literal}`);
      }
    }
    lines.push("");
  }

  if (
    doc.stats.length === 0 &&
    doc.variables.length === 0 &&
    doc.items.length === 0 &&
    npcs.npcs.length === 0
  ) {
    lines.push(
      "// Nothing declared yet. Add stats, vars or items in Game > Variables.",
    );
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * A string as the contents of an ink literal.
 *
 * Ink has no escape for a quote inside a string, so one is dropped rather than
 * allowed to end the literal early and break every declaration after it. Same
 * rule as `initialLiteral`, and for the same reason.
 */
function inkString(value: string): string {
  return value.replace(/"/g, "");
}

/**
 * Adds `INCLUDE state.ink` to an entry point that lacks it.
 *
 * Placed above any existing INCLUDE, and before the first divert — ink requires
 * declarations to be reachable at load, and a file that opens with `-> start`
 * would otherwise never read them. Returns the source unchanged when the include
 * is already there, so this is safe to run on every regeneration.
 */
export function withStateInclude(
  entrySource: string,
  entryPath: string,
): string {
  const relative = includePathFrom(entryPath);
  const pattern = new RegExp(
    `^[ \\t]*INCLUDE[ \\t]+${escapeRegExp(relative)}[ \\t]*$`,
    "m",
  );
  if (pattern.test(entrySource)) return entrySource;

  const lines = entrySource.split(/\r?\n/);
  const firstInclude = lines.findIndex((line) => /^[ \t]*INCLUDE\b/.test(line));
  const at = firstInclude !== -1 ? firstInclude : afterLeadingComments(lines);

  lines.splice(
    at,
    0,
    `INCLUDE ${relative}`,
    ...(firstInclude === -1 ? [""] : []),
  );
  return lines.join("\n");
}

/**
 * `state.ink` as reached from the entry point.
 *
 * ink resolves an INCLUDE relative to the file doing the including — which is
 * why `ink/main.ink` reaches its sibling as `characters.ink` — so this is an
 * ordinary relative path, not a project-relative one.
 */
export function includePathFrom(entryPath: string): string {
  const from = entryPath.split("/").slice(0, -1);
  const to = STATE_FILE.split("/");

  let common = 0;
  while (
    common < from.length &&
    common < to.length - 1 &&
    from[common] === to[common]
  )
    common++;

  const up = "../".repeat(from.length - common);
  return `${up}${to.slice(common).join("/")}`;
}

function afterLeadingComments(lines: string[]): number {
  let at = 0;
  while (at < lines.length && /^[ \t]*(?:\/\/.*)?$/.test(lines[at]!)) at++;
  return at;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
