import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { createWriteStream } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pipeline } from 'node:stream/promises'
import { ZipFile } from 'yazl'
import { PACKAGE_FORMAT, PACKAGE_MANIFEST } from '@shared/projectPackage'
import type { CodexLibrary, Project } from '@shared/project'
import {
  entryNames,
  entryText,
  importPackage,
  packageFileName,
  packageProject,
  previewPackage
} from './projectPackage'
import { exists } from './fs'
import { listProjects } from './project'

/**
 * The round trip, over real files and a real zip: a workspace is packaged, the
 * package is opened into a second workspace, and what lands there is read back.
 *
 * The cases that matter most are the ones where the two workspaces disagree —
 * a folder name already taken, a library already present, the same project
 * opened twice — because those are what a package meets when it arrives
 * somewhere that is not empty, which is the normal case.
 */

let root = ''
let from = ''
let to = ''
let out = ''
let project: Project
let cast: CodexLibrary

/** A workspace with one project and one library, both written the way the app writes them. */
async function makeWorkspace(dir: string): Promise<{ project: Project; library: CodexLibrary }> {
  const projectPath = join(dir, 'projects', 'the-archive')
  await mkdir(join(projectPath, 'ink'), { recursive: true })
  await mkdir(join(projectPath, 'media', 'bg'), { recursive: true })
  await mkdir(join(projectPath, 'export'), { recursive: true })
  await writeFile(
    join(projectPath, 'project.md'),
    '---\nid: prj_0000000001\ntitle: The Archive\nlibraries:\n  - lib_0000000001\nmain: ink/main.ink\n---\n\nA night archivist.\n',
    'utf8'
  )
  await writeFile(join(projectPath, 'ink', 'main.ink'), '-> start\n\n=== start ===\nDust.\n-> END\n', 'utf8')
  await writeFile(join(projectPath, 'stats.json'), '{"version":1}', 'utf8')
  await writeFile(join(projectPath, 'media', 'bg', 'hall.png'), 'png bytes', 'utf8')
  // Generated on save, and regenerated by any export: a build output that
  // happens to live in the source folder.
  await writeFile(join(projectPath, 'export', 'catalogue.json'), '{"stale":true}', 'utf8')
  // Whatever the author's other tools left behind.
  await writeFile(join(projectPath, '.DS_Store'), 'finder', 'utf8')

  const libraryPath = join(dir, 'codex', 'archive-world')
  await mkdir(libraryPath, { recursive: true })
  await writeFile(
    join(libraryPath, 'library.md'),
    '---\nid: lib_0000000001\ntitle: Archive world\n---\n\nThe world.\n',
    'utf8'
  )
  await writeFile(join(libraryPath, 'wren.md'), '---\nid: cdx_0000000001\nname: Wren\n---\n\nA keeper.\n', 'utf8')

  return {
    project: {
      id: 'prj_0000000001',
      title: 'The Archive',
      libraries: ['lib_0000000001'],
      main: 'ink/main.ink',
      description: 'A night archivist.',
      bundleOut: null,
      path: projectPath
    },
    library: {
      id: 'lib_0000000001',
      title: 'Archive world',
      description: 'The world.',
      path: libraryPath,
      entryCount: 1
    }
  }
}


/**
 * A zip built by hand, because yazl will not write one of these.
 *
 * yazl refuses an entry named `../x` or `/etc/passwd` outright, which is the
 * right thing for a writer and leaves no way to produce the archive a hostile
 * sender would. So these bytes are assembled here: stored entries, a central
 * directory, an end record. Only what these tests need.
 */
function rawZip(entries: { name: string; body: string }[]): Buffer {
  const locals: Buffer[] = []
  const central: Buffer[] = []
  let offset = 0

  for (const entry of entries) {
    const name = Buffer.from(entry.name, 'utf8')
    const body = Buffer.from(entry.body, 'utf8')
    const crc = crc32(body)

    const local = Buffer.alloc(30 + name.length)
    local.writeUInt32LE(0x04034b50, 0)
    local.writeUInt16LE(10, 4) // version needed
    local.writeUInt16LE(0, 6) // flags
    local.writeUInt16LE(0, 8) // stored, not deflated
    local.writeUInt32LE(crc, 14)
    local.writeUInt32LE(body.length, 18)
    local.writeUInt32LE(body.length, 22)
    local.writeUInt16LE(name.length, 26)
    name.copy(local, 30)
    locals.push(local, body)

    const middle = Buffer.alloc(46 + name.length)
    middle.writeUInt32LE(0x02014b50, 0)
    middle.writeUInt16LE(20, 4) // version made by
    middle.writeUInt16LE(10, 6) // version needed
    middle.writeUInt16LE(0, 10) // stored
    middle.writeUInt32LE(crc, 16)
    middle.writeUInt32LE(body.length, 20)
    middle.writeUInt32LE(body.length, 24)
    middle.writeUInt16LE(name.length, 28)
    middle.writeUInt32LE(offset, 42)
    name.copy(middle, 46)
    central.push(middle)

    offset += local.length + body.length
  }

  const directory = Buffer.concat(central)
  const end = Buffer.alloc(22)
  end.writeUInt32LE(0x06054b50, 0)
  end.writeUInt16LE(entries.length, 8)
  end.writeUInt16LE(entries.length, 10)
  end.writeUInt32LE(directory.length, 12)
  end.writeUInt32LE(offset, 16)

  return Buffer.concat([...locals, directory, end])
}

/** The one table zip uses, computed here so the test needs no dependency for it. */
function crc32(body: Buffer): number {
  let crc = 0xffffffff
  for (const byte of body) {
    crc ^= byte
    for (let bit = 0; bit < 8; bit += 1) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1
  }
  return (crc ^ 0xffffffff) >>> 0
}

/** The manifest a hostile package would carry, so the entry check is what fires. */
const TROUBLE = JSON.stringify({
  format: PACKAGE_FORMAT,
  project: { id: 'prj_0000000009', title: 'Trouble', folder: 'trouble' },
  libraries: []
})

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'inkcrafter-package-'))
  from = join(root, 'here')
  to = join(root, 'there')
  out = join(root, 'the-archive.zip')
  await mkdir(join(to, 'projects'), { recursive: true })
  await mkdir(join(to, 'codex'), { recursive: true })
  const made = await makeWorkspace(from)
  project = made.project
  cast = made.library
})

afterEach(async () => {
  await rm(root, { recursive: true, force: true })
})

describe('packageProject', () => {
  it('writes the project and the libraries it was given, and nothing generated', async () => {
    const result = await packageProject(project, [cast], out)

    expect(result.ok).toBe(true)
    expect(result.problem).toBeNull()
    expect(result.warnings).toEqual([])
    expect(result.bytes).toBeGreaterThan(0)

    expect(await entryNames(out)).toEqual([
      'codex/archive-world/library.md',
      'codex/archive-world/wren.md',
      PACKAGE_MANIFEST,
      'project/ink/main.ink',
      'project/media/bg/hall.png',
      'project/project.md',
      'project/stats.json'
    ])
    expect(result.files).toBe(7)

    expect(JSON.parse((await entryText(out, PACKAGE_MANIFEST))!)).toMatchObject({
      format: PACKAGE_FORMAT,
      project: { id: 'prj_0000000001', title: 'The Archive', folder: 'the-archive' },
      libraries: [{ id: 'lib_0000000001', title: 'Archive world', folder: 'archive-world' }]
    })
    expect(await entryText(out, 'project/media/bg/hall.png')).toBe('png bytes')
  })

  // The one thing about a package that cannot be seen afterwards: opened
  // somewhere else, a story with no codex behind it looks like a broken story.
  it('says so when the project links a library that is not going in', async () => {
    const result = await packageProject(project, [], out)

    expect(result.ok).toBe(true)
    expect(result.warnings.join(' ')).toContain('lib_0000000001')
    expect(await entryNames(out)).not.toContain('codex/archive-world/library.md')
  })

  it('leaves nothing behind when it cannot write', async () => {
    // A folder cannot be made inside a file, so this is a destination no
    // amount of mkdir will produce.
    const blocked = join(root, 'notes.txt')
    await writeFile(blocked, 'in the way', 'utf8')

    const result = await packageProject(project, [cast], join(blocked, 'the-archive.zip'))

    expect(result.ok).toBe(false)
    expect(result.problem).not.toBeNull()
    expect(await readFile(blocked, 'utf8')).toBe('in the way')
  })

  it('names the file after the project', () => {
    expect(packageFileName(project)).toBe('the-archive.zip')
    expect(packageFileName({ ...project, title: 'Wren & Sparrow' })).toBe('wren-sparrow.zip')
  })
})

describe('previewPackage', () => {
  it('says what is inside without writing anything', async () => {
    await packageProject(project, [cast], out)

    const preview = await previewPackage(out, to)

    expect(preview.ok).toBe(true)
    expect(preview.manifest?.project.title).toBe('The Archive')
    expect(preview.folder).toBe('the-archive')
    expect(preview.duplicate).toBe(false)
    expect(preview.libraries).toEqual([
      {
        id: 'lib_0000000001',
        title: 'Archive world',
        folder: 'archive-world',
        fate: 'add',
        existingTitle: null
      }
    ])
    expect(await listProjects(join(to, 'projects'))).toEqual([])
  })

  it('refuses a zip that is not a package, and says which it is', async () => {
    const zip = new ZipFile()
    zip.addBuffer(Buffer.from('not a package', 'utf8'), 'notes.txt')
    zip.end()
    const plain = join(root, 'plain.zip')
    await pipeline(zip.outputStream, createWriteStream(plain))

    const preview = await previewPackage(plain, to)

    expect(preview.ok).toBe(false)
    expect(preview.problem).toContain('a zip rather than a project package')
  })

  it('refuses a file that is not a zip at all', async () => {
    const text = join(root, 'story.txt')
    await writeFile(text, 'once upon a time', 'utf8')

    expect((await previewPackage(text, to)).ok).toBe(false)
  })

  it('refuses a package from a format it does not know', async () => {
    const zip = new ZipFile()
    zip.addBuffer(
      Buffer.from(JSON.stringify({ format: 'inkcrafter-package/99' }), 'utf8'),
      PACKAGE_MANIFEST
    )
    zip.end()
    const future = join(root, 'future.zip')
    await pipeline(zip.outputStream, createWriteStream(future))

    expect((await previewPackage(future, to)).problem).toContain('inkcrafter-package/99')
  })
})

describe('importPackage', () => {
  it('puts the project and its library into the workspace', async () => {
    await packageProject(project, [cast], out)

    const result = await importPackage(out, to)

    expect(result.ok).toBe(true)
    expect(result.problem).toBeNull()
    expect(result.warnings).toEqual([])
    expect(result.projectPath).toBe(join(to, 'projects', 'the-archive'))
    expect(result.libraries).toEqual([{ title: 'Archive world', fate: 'add' }])

    expect(await readFile(join(to, 'projects', 'the-archive', 'ink', 'main.ink'), 'utf8')).toContain('Dust.')
    expect(await readFile(join(to, 'projects', 'the-archive', 'media', 'bg', 'hall.png'), 'utf8')).toBe('png bytes')
    expect(await readFile(join(to, 'codex', 'archive-world', 'wren.md'), 'utf8')).toContain('A keeper.')

    // The workspace lists it as a project, which is the actual claim: the
    // files landing is only useful if the app can then open them.
    const projects = await listProjects(join(to, 'projects'))
    expect(projects.map((one) => one.title)).toEqual(['The Archive'])
    expect(projects[0]!.libraries).toEqual(['lib_0000000001'])

    // The staging folder is not left in the workspace to be listed as a project.
    expect(await exists(join(to, '.inkcrafter-opening'))).toBe(false)
  })

  it('keeps the library the workspace already has rather than the sender’s', async () => {
    await packageProject(project, [cast], out)
    const theirs = await makeWorkspace(to)
    await writeFile(join(theirs.library.path, 'wren.md'), 'my own notes about Wren\n', 'utf8')

    const result = await importPackage(out, to)

    expect(result.ok).toBe(true)
    expect(result.libraries).toEqual([{ title: 'Archive world', fate: 'keep' }])
    expect(result.warnings.join(' ')).toContain('Kept the codex library you already have')
    expect(await readFile(join(theirs.library.path, 'wren.md'), 'utf8')).toBe('my own notes about Wren\n')
    expect(await exists(join(to, 'codex', 'archive-world-2'))).toBe(false)
  })

  // Two projects under one id would share the player's save slots, since a
  // save names the story it belongs to by that id.
  it('gives a second copy of the same project its own folder and identity', async () => {
    await packageProject(project, [cast], out)
    await makeWorkspace(to)

    const preview = await previewPackage(out, to)
    expect(preview.duplicate).toBe(true)
    expect(preview.folder).toBe('the-archive-2')

    const result = await importPackage(out, to)

    expect(result.ok).toBe(true)
    expect(result.projectPath).toBe(join(to, 'projects', 'the-archive-2'))
    expect(result.warnings.join(' ')).toContain('given a new identity')

    const projects = await listProjects(join(to, 'projects'))
    expect(projects.map((one) => one.title)).toEqual(['The Archive', 'The Archive'])
    expect(new Set(projects.map((one) => one.id)).size).toBe(2)
  })

  it('opens a package into a workspace that has never been used', async () => {
    await packageProject(project, [cast], out)
    const fresh = join(root, 'fresh')

    const result = await importPackage(out, fresh)

    expect(result.ok).toBe(true)
    expect(await exists(join(fresh, 'projects', 'the-archive', 'project.md'))).toBe(true)
    expect(await exists(join(fresh, 'codex', 'archive-world', 'library.md'))).toBe(true)
  })

  /*
   * A package can arrive from anybody, and a zip may name its entries anything
   * at all. These are the two names that turn an unpacker into a way of writing
   * wherever the sender chose.
   */
  it('refuses an entry that climbs out of the package, writing nothing', async () => {
    const hostile = join(root, 'hostile.zip')
    await writeFile(
      hostile,
      rawZip([
        { name: PACKAGE_MANIFEST, body: TROUBLE },
        { name: '../../escaped.txt', body: 'owned' }
      ])
    )

    const preview = await previewPackage(hostile, to)
    expect(preview.ok).toBe(false)
    // yauzl will not hand over an entry named like this at all, so the reason
    // may be its words rather than ours. The refusal, and the entry, are the
    // part that matters.
    expect(preview.problem).toContain('is not a package this will open')
    expect(preview.problem).toContain('escaped.txt')

    const result = await importPackage(hostile, to)
    expect(result.ok).toBe(false)
    expect(await exists(join(root, 'escaped.txt'))).toBe(false)
    expect(await exists(join(to, 'projects', 'trouble'))).toBe(false)
  })

  it('refuses an absolute entry name', async () => {
    const hostile = join(root, 'absolute.zip')
    await writeFile(
      hostile,
      rawZip([
        { name: PACKAGE_MANIFEST, body: TROUBLE },
        { name: '/etc/passwd', body: 'owned' }
      ])
    )

    expect((await previewPackage(hostile, to)).problem).toContain('absolute path')
  })

  it('refuses an entry that belongs to no part of a package', async () => {
    const odd = join(root, 'odd.zip')
    await writeFile(
      odd,
      rawZip([
        { name: PACKAGE_MANIFEST, body: TROUBLE },
        { name: 'somewhere/else.txt', body: 'stray' }
      ])
    )

    expect((await previewPackage(odd, to)).problem).toContain('is not part of a project package')
  })

  it('refuses a package whose project half is missing', async () => {
    const zip = new ZipFile()
    zip.addBuffer(
      Buffer.from(
        JSON.stringify({
          format: PACKAGE_FORMAT,
          project: { id: 'prj_0000000009', title: 'Hollow', folder: 'hollow' },
          libraries: []
        }),
        'utf8'
      ),
      PACKAGE_MANIFEST
    )
    zip.addBuffer(Buffer.from('orphan', 'utf8'), 'project/ink/main.ink')
    zip.end()
    const hollow = join(root, 'hollow.zip')
    await pipeline(zip.outputStream, createWriteStream(hollow))

    const result = await importPackage(hollow, to)

    expect(result.ok).toBe(false)
    expect(result.problem).toContain('no project.md')
    expect(await exists(join(to, 'projects', 'hollow'))).toBe(false)
  })
})
